name = "StringAlgorithms"
uuid = "363485be-8d8f-4fd8-b080-16cbc6247135"
authors = ["Greg Lapinski <grzegorz.lapinski@live.com>"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
